const crystals = [
		{
			name: "Amethyst",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603199254/Crystals/Amethyst_tir0fc.jpg",
			energy: "Amplifies",
			chakra: "Third eye | Crown",
			helps: "Intuition and insight | insomnia | Safe travel | Connecting to higher self & Divine | Creativity | Manifestation | Stress & anxiety | Nightmares | Addiction",
			placement: "Place on third eye chakra | above crown of head | near your bed | under pillow",
			bkgColor: " to bottom right, hsla(295, 82%, 19%, 1), hsla(342, 82%, 63%, 1)",
			visible: false,
		},
		{
			name: "Black Tourmaline",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603593580/Crystals/black-tourmaline_ok2upr.jpg",
			energy: "Absorbs",
			chakra: "Root",
			helps: "Psychic Protection | Protect Against Negativity | Grounding | Stress Release | Cleansing Negative Emotions",
			placement: "Pants pocket | Near root chakra | Next to bed | Between you & source of negativity",
			bkgColor: " to bottom right, hsla(360, 82%, 12%, 1), hsla(200, 87%, 22%, 1)",
			visible: false,
		},
		{
			name: "Citrine",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603832011/Crystals/grant-durr-oeGg2Z_qm1o-unsplash_qcyqbi.jpg",
			energy: "Amplifies",
			chakra: "Solar Plexus",
			helps: "Prosperity | Self-Esteem | Creativity | Encourages Generosity | Clarity of Thinking | Manifestation",
			placement: "On or near solar plexus | On a bracelet, ring, necklace | In wallet",
			bkgColor: " to bottom right, hsla(40, 82%, 40%, 1), hsla(50, 82%, 45%, 1) ",
			visible: false,
		},
		 {
			name: "Clear Quartz",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603833038/Crystals/clear_quartz_uyw842.jpg",
			energy: "Amplifies",
			chakra: "Crown | All others (secondary)",
			helps: "Amplfies Properties of All Other Crystals | Protection | Amplifies Energy & Thoguht | Improves Concetration",
			placement: "Anywhere for meditation | Near crown | In grid with other crystals",
			bkgColor: " to bottom right, hsla(50, 82%, 42%, 0.84), hsla(196, 82%, 42%, 0.94)",
			visible: false,
		},
		{
			name: "Emerald",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603834551/Emerald_enpzip.jpg",
			energy: "Amplifies",
			chakra: "Heart",
			helps: "Prosperity | Unconditional Love | Compassion | Romance | Kindness & Forgiveness | Increase Spiritual Awareness",
			placement: "On heart chakra | In jewelry | Commitment finger in a ring",
			bkgColor: " to bottom right, hsla(131, 82%, 40%, 1), hsla(114, 98%, 50%, 1)",
			visible: false,
		},
		{
			name: "Fluorite",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603833728/Crystals/Fluorite_kc6c8c.jpg",
			energy: "Absorbs",
			chakra: "Heart | Throat | Third Eye | Crown",
			helps: "Balancing Energy | Intuition | Calming | Enhancing Creativity | Harmonizing",
			placement: "Anywhere on four stated chakras | Necklace",
			bkgColor: " to bottom right, hsla(151, 82%, 42%, 1), hsla(151, 82%, 22%, 1)",
			visible: false,
		},
        {
			name: "Kyanite",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603646925/Crystals/Kyanite_o5nzp0.jpg",
			energy: "Dosen't hold energy",
			chakra: "Green - Heart | Blue - Throat",
			helps: "Creating Pathways from One Thing to Another | Clearing Blockage | Loyalty & Fairness | Memory Recall",
			placement: "On corresponding chakras | In your hand",
			bkgColor: " to bottom right, hsla(242, 82%, 27%, 1), hsla(242, 82%, 35%, 1)",
			visible: false,
		},
        {
			name: "Labradorite",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603655431/Crystals/Labradorite_wbnb5c.jpg",
			energy: "Amplifies",
			chakra: "Throat | Third Eye",
			helps: "Amplify Magical Qualites | Reducing Negativity | Detoxification of Addictive Substances | Tempering Impulsivity | Aiding Inuition",
			placement: "On throat chakra | As a necklace | Near area of meditation",
			bkgColor: " to bottom right, hsla(126, 82%, 23%, 1), hsla(160, 82%, 26%, 1) ",
			visible: false,
		},
		 {
			name: "Red Jasper",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603834082/Crystals/Red_Jasper_pp8yvc.jpg",
			energy: "Absorb",
			chakra: "Root",
			helps: "Manifestation | Balancing Energies of Excess | Grounding | Sability",
			placement: "On root chakra | In jewelry | In pocket",
			bkgColor: " to bottom right, hsla(13, 82%, 26%, 1), hsla(360, 82%, 41%, 1)",
			visible: false,
		},
		{
			name: "Rose Quartz",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603199255/rose-quartz_i9biui.jpg",
			energy: "Amplifies",
			chakra: "Heart",
			helps: "Compassion | Kindness | Unconditional Love | Self-Love | Emotional Healing | Joy | Peace | Playfulness",
			placement: " On a necklace | Bracelet | Ring (commitment finger) | Heart chakra",
			bkgColor: " to bottom right, hsla(360, 96%, 46%, 1), hsla(312, 96%, 67%, 1)",
			visible: false,
		},
        {
			name: "Selenite",
			image: "https://res.cloudinary.com/begottenson/image/upload/c_scale,w_400/v1603656125/Crystals/Selenite_nwvb4q.jpg",
			energy: "Amplifies",
			chakra: "Third Eye | Crown",
			helps: "Protecting Against Negativity | Cleansing Negative Energy | Cleansing Other Crystals & Aura | Connect with Intuition",
			placement: "On or near the third eye or crown chakra",
			bkgColor: " to bottom right, hsla(307, 82%, 24%, 1), hsla(280, 82%, 69%, 1) ",
			visible: false,
		}
	];

// TEMPLATE TO PLACE IN CRYSTALS VARIBLE
    // {
	// 		name: "",
	// 		image: "",
	// 		energy: "",
	// 		chakra: "",
	// 		helps: "",
	// 		placement: "",
	// 		bkgColor: " to bottom right, ",
	// 		visible: false,
	// 	},

    export default crystals;